backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "" # Media files will be stored in the repo under images/uploads

site_url: https://hanminart.netlify.app
logo_url: https://res.cloudinary.com/ds2o5ecdw/image/upload/v1652474773/han_min/lotus_twemoji.png
search: false

collections:
  # Portfolio posts
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    description: "Add new paintings to your portfolio"
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date first posted", name: "date", widget: "date" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Dimensions", name: "dimensions", widget: "string" }
      - { label: "Media", name: "media", widget: "string" }
      - { label: "Cloudinary image link", name: "image", widget: "string"}
      - { label: "Show big image?", name: "big_image", widget: "boolean", default: true}
      - { label: "Tags", name: "tags", widget: "hidden", default: "posts" }
    sortable_fields: ['date', 'title']